### ISSUE TITLE
error when doing automatic deployment

### ISSUE THREAD

**Issue by talmax1124** [sanity-io/sanity-template-nextjs-blog-comments#6]
12:55:40 | Cloning github.com/talmax1124/next-js-blog-with-commentss (Branch: master, Commit: 29ef494)
-- | --
12:55:41 | Cloning completed: 520.45ms
12:55:41 | Analyzing source code...
12:55:42 | Installing build runtime...
12:55:44 | Build runtime installed: 2.099s
12:55:47 | Looking up build cache...
12:55:47 | Build cache not found
12:55:48 | Installing dependencies...
12:56:08 | > cms-sanity@1.0.0 postinstall /vercel/path0
12:56:08 | > lerna bootstrap
12:56:09 | lerna notice cli v3.22.1
12:56:09 | lerna info ci enabled
12:56:09 | lerna info Bootstrapping 1 package
12:56:09 | lerna info Installing external dependencies
12:56:20 | lerna info Symlinking packages and binaries
12:56:20 | lerna success Bootstrapped 1 package
12:56:21 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
12:56:21 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
12:56:21 | npm WARN cssnano-simple@2.0.0 requires a peer of postcss@^8.2.2 but none is installed. You must install peer dependencies yourself.
12:56:21 | npm WARN cssnano-preset-simple@2.0.0 requires a peer of postcss@^8.2.1 but none is installed. You must install peer dependencies yourself.
12:56:21 | npm WARN cms-sanity@1.0.0 No repository field.
12:56:21 | npm WARN cms-sanity@1.0.0 No license field.
12:56:21 | added 1142 packages from 551 contributors in 32.63s
12:56:22 | 75 packages are looking for funding
12:56:22 | run `npm fund` for details
12:56:22 | Detected Next.js version: 10.2.0
12:56:22 | Running "npm run build"
12:56:22 | > cms-sanity@1.0.0 build /vercel/path0
12:56:22 | > npm run build:sanity && pwd && npm run build:web
12:56:22 | > cms-sanity@1.0.0 build:sanity /vercel/path0
12:56:22 | > cd studio && sanity build ../public/studio -y && cd ..
12:56:23 | Including the following environment variables as part of the JavaScript bundle:
12:56:23 | - SANITY_STUDIO_API_PROJECT_ID
12:56:23 | - SANITY_STUDIO_API_DATASET
12:56:24 | Browserslist: caniuse-lite is outdated. Please run:
12:56:24 | npx browserslist@latest --update-db
12:56:24 | Why you should do it regularly:
12:56:24 | https://github.com/browserslist/browserslist#browsers-data-updating
12:57:03 | /vercel/path0
12:57:03 | > cms-sanity@1.0.0 build:web /vercel/path0
12:57:03 | > next build
12:57:04 | warn  - React 17.0.1 or newer will be required to leverage all of the upcoming features in Next.js 11. Read more: https://nextjs.org/docs/messages/react-version
12:57:04 | info  - Using webpack 5. Reason: no custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
12:57:04 | info  - Checking validity of types...
12:57:04 | Attention: Next.js now collects completely anonymous telemetry regarding usage.
12:57:04 | This information is used to shape Next.js' roadmap and prioritize features.
12:57:04 | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
12:57:04 | https://nextjs.org/telemetry
12:57:04 | info  - Creating an optimized production build...
12:57:08 | Browserslist: caniuse-lite is outdated. Please run:
12:57:08 | npx browserslist@latest --update-db
12:57:09 | warn - Tailwind is not purging unused styles because no template paths have been provided.
12:57:09 | warn - If you have manually configured PurgeCSS outside of Tailwind or are deliberately not removing unused styles, set `purge: false` in your Tailwind config file to silence this warning.
12:57:09 | warn - https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
12:57:19 | Failed to compile.
12:57:19 | HookWebpackError: [object Object] is not a PostCSS plugin
12:57:19 | > Build error occurred
12:57:19 | Error: > Build failed because of webpack errors
12:57:19 | at /vercel/path0/node_modules/next/dist/build/index.js:17:924
12:57:19 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:6:584)
12:57:19 | npm ERR! code ELIFECYCLE
12:57:19 | npm ERR! errno 1
12:57:19 | npm ERR! cms-sanity@1.0.0 build:web: `next build`
12:57:19 | npm ERR! Exit status 1
12:57:19 | npm ERR!
12:57:19 | npm ERR! Failed at the cms-sanity@1.0.0 build:web script.
12:57:19 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
12:57:19 | npm ERR! A complete log of this run can be found in:
12:57:19 | npm ERR!     /vercel/.npm/_logs/2021-04-30T16_57_19_161Z-debug.log
12:57:19 | npm ERR! code ELIFECYCLE
12:57:19 | npm ERR! errno 1
12:57:19 | npm ERR! cms-sanity@1.0.0 build: `npm run build:sanity && pwd && npm run build:web`
12:57:19 | npm ERR! Exit status 1
12:57:19 | npm ERR!
12:57:19 | npm ERR! Failed at the cms-sanity@1.0.0 build script.
12:57:19 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
12:57:19 | npm ERR! A complete log of this run can be found in:
12:57:19 | npm ERR!     /vercel/.npm/_logs/2021-04-30T16_57_19_181Z-debug.log
12:57:19 | Error: Command "npm run build" exited with 1

**Comment by p10e** [comment]
Thanks for reporting, @talmax1124! This should now be fixed in the latest version of the template at https://www.sanity.io/create?template=sanity-io%2Fsanity-template-nextjs-blog-comments.
